package presentation;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class BolaPalettePanel implements Observer {

    /**
     * Panell contenidor
     */
    private JPanel panel;

    /**
     * Botó amb el color NUL
     */
    private BolaButton buttonNul;

    /**
     * Botó amb el color BLANC
     */
    private BolaButton buttonBlanc;

    /**
     * Botó amb el color NEGRE
     */
    private BolaButton buttonNegre;

    /**
     * Botó amb el color VERMELL
     */
    private BolaButton buttonVermell;

    /**
     * Botó amb el color BLAU
     */
    private BolaButton buttonBlau;

    /**
     * Botó amb el color TARONJA
     */
    private BolaButton buttonTaronja;

    /**
     * Botó amb el color ROSA
     */
    private BolaButton buttonRosa;

    /**
     * Llista amb els botons dels colors
     */
    private final List<BolaButton> buttonBolaList;

    /**
     * Color del botó seleccionat
     */
    private BolaColor selectedColor;


    /**
     * Constructor per defecte del panell
     */
    BolaPalettePanel() {
        $$$setupUI$$$();
        buttonBolaList = new ArrayList<>(List.of(buttonNul, buttonBlanc, buttonNegre, buttonVermell, buttonBlau, buttonTaronja, buttonRosa));
        initComponents();
    }

    /**
     * Mètode per inicialitzar els components interns del panell
     */
    private void initComponents() {
        buttonNul.setBolaColor(BolaColor.NUL);
        buttonBlanc.setBolaColor(BolaColor.BLANC);
        buttonNegre.setBolaColor(BolaColor.NEGRE);
        buttonVermell.setBolaColor(BolaColor.VERMELL);
        buttonBlau.setBolaColor(BolaColor.BLAU);
        buttonTaronja.setBolaColor(BolaColor.TARONJA);
        buttonRosa.setBolaColor(BolaColor.ROSA);

        for (int i = 0; i < buttonBolaList.size(); i++) {
            buttonBolaList.get(i).setID("P" + i);
            buttonBolaList.get(i).Attach(this);
            buttonBolaList.get(i).setBorder(false);
        }
    }

    /**
     * Mètode per saber si hi ha cap color seleccionat
     */
    Boolean isColorSelected() {
        return selectedColor != null;
    }

    /**
     * Getter del color seleccionat
     */
    BolaColor getSelectedColor() {
        return selectedColor;
    }

    /**
     * Mètode per desseleccionar tots els colors
     */
    void unselectAllColors() {
        for (BolaButton button : buttonBolaList)
            button.setBorder(false);
        selectedColor = null;
    }

    /**
     * Mètode de l'observador, s'executa quan es clica un dels botons del panell
     */
    @Override
    public void Update(Subject s) {
        int id = Integer.parseInt(((BolaButton) s).getID().substring(1));
        unselectAllColors();
        buttonBolaList.get(id).setBorder(true);
        selectedColor = buttonBolaList.get(id).getBolaColor();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        buttonNul = new BolaButton();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(buttonNul.$$$getRootComponent$$$(), gbc);
        buttonBlanc = new BolaButton();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panel.add(buttonBlanc.$$$getRootComponent$$$(), gbc);
        buttonNegre = new BolaButton();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel.add(buttonNegre.$$$getRootComponent$$$(), gbc);
        buttonVermell = new BolaButton();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        panel.add(buttonVermell.$$$getRootComponent$$$(), gbc);
        buttonBlau = new BolaButton();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        panel.add(buttonBlau.$$$getRootComponent$$$(), gbc);
        buttonTaronja = new BolaButton();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        panel.add(buttonTaronja.$$$getRootComponent$$$(), gbc);
        buttonRosa = new BolaButton();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        panel.add(buttonRosa.$$$getRootComponent$$$(), gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
