package presentation;

import javax.swing.*;
import java.awt.*;

/**
 * Vista inicial per a un usuari registrat
 * @author Mar Gonzàlez Català
 */
public class HomeView {

    /**
     * Controlador de presentació
     */
    private final ControladorPresentacio controladorPresentacio;

    /**
     * Panell contenidor
     */
    private JPanel panel;

    /**
     * Botó per crear una nova partida
     */
    private JButton buttonNovaPartida;

    /**
     * Botó per carregar una partida a mitges
     */
    private JButton buttonCarregarPartida;

    /**
     * Botó per accedir a la zona d'usuari
     */
    private JButton buttonZonaUsuari;

    /**
     * Botó per veure el rànquing
     */
    private JButton buttonRanquing;

    /**
     * Botó per tancar sessió i tornar a la pantalla d'inici
     */
    private JButton buttonSortir;

    /**
     * Botó per veure les normes
     */
    private JButton buttonNormes;

    /**
     * Constructor per defecte de la vista
     */
    HomeView() {
        controladorPresentacio = ControladorPresentacio.getInstance();
        $$$setupUI$$$();
        initComponents();
    }

    /**
     * Mètode per mostrar la vista
     */
    void show() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Benvinguda");
    }

    /**
     * Mètode per inicialitzar els components de la vista
     */
    private void initComponents() {
        if (!controladorPresentacio.existsPartidaGuardada()) {
            buttonCarregarPartida.setEnabled(false);
        }
        buttonRanquing.addActionListener(actionEvent -> controladorPresentacio.showRankingView());
        buttonNormes.addActionListener(actionEvent -> controladorPresentacio.showNormesView());
        buttonNovaPartida.addActionListener(actionEvent -> controladorPresentacio.showNovaPartidaView());
        buttonCarregarPartida.addActionListener(actionEvent -> carregarPartidaButtonClick());
        buttonSortir.addActionListener(actionEvent -> sortirButtonClick());
        buttonZonaUsuari.addActionListener(actionEvent -> controladorPresentacio.showEstadistiquesView());
    }

    /**
     * Mètode que efectua les accions pertinents en clicar el botó per sortir
     */
    private void sortirButtonClick() {
        controladorPresentacio.logoutUser();
        controladorPresentacio.showInitialView();
    }

    /**
     * Mètode que efectua les accions pertinents en clicar el botó per carregar una partida
     */
    private void carregarPartidaButtonClick() {
        controladorPresentacio.carregarPartida();
        if (controladorPresentacio.isJugadorBreaker())
            controladorPresentacio.showPartidaBreakerView();
        else
            controladorPresentacio.showPartidaMakerView();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel.add(panel1, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.WEST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel2.add(panel3);
        buttonSortir = new JButton();
        buttonSortir.setText("Sortir");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(buttonSortir, gbc);
        buttonNormes = new JButton();
        buttonNormes.setText("Normes");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(buttonNormes, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel4, BorderLayout.EAST);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridBagLayout());
        panel4.add(panel5);
        buttonZonaUsuari = new JButton();
        buttonZonaUsuari.setText("Estadístiques");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(buttonZonaUsuari, gbc);
        buttonRanquing = new JButton();
        buttonRanquing.setText("Rànquing");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel5.add(buttonRanquing, gbc);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridBagLayout());
        panel.add(panel6, BorderLayout.CENTER);
        buttonNovaPartida = new JButton();
        buttonNovaPartida.setText("Nova Partida");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(buttonNovaPartida, gbc);
        buttonCarregarPartida = new JButton();
        buttonCarregarPartida.setText("Carregar Partida");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel6.add(buttonCarregarPartida, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
