package presentation;

import javax.swing.*;
import java.awt.*;

/**
 * Vista inicial per a un usuari registrat
 *
 * @author Mar Gonzàlez Català
 */
public class HomeView {
    private final ControladorPresentacio controladorPresentacio;
    private JPanel panel;
    private JButton buttonZonaUsuari;
    private JButton buttonNormes;
    private JButton buttonRanquing;
    private JButton buttonNovaPartida;
    private JButton buttonCarregarPartida;

    HomeView(ControladorPresentacio controladorPresentacio) {
        this.controladorPresentacio = controladorPresentacio;
        $$$setupUI$$$();
        initComponents();
    }

    void show() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Mastermind");
    }

    private void initComponents() {
        buttonRanquing.addActionListener(actionEvent -> controladorPresentacio.showInitialView());
        buttonNormes.addActionListener(actionEvent -> controladorPresentacio.showInitialView());
        buttonNovaPartida.addActionListener(actionEvent -> controladorPresentacio.showNovaPartidaView());
        buttonCarregarPartida.addActionListener(actionEvent -> carregarPartidaButtonClick());
        buttonZonaUsuari.addActionListener(actionEvent -> controladorPresentacio.showInitialView());
    }

    private void carregarPartidaButtonClick() {
        if (!controladorPresentacio.existsPartidaGuardada()) {
            controladorPresentacio.showWarningDialog("Could not charge game", "There is no game saved");
        } else {
            controladorPresentacio.carregarPartida();
            controladorPresentacio.showHomeView();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel.add(panel1, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel1.add(panel2, BorderLayout.WEST);
        buttonZonaUsuari = new JButton();
        buttonZonaUsuari.setText("Zona Usuari");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonZonaUsuari, gbc);
        buttonRanquing = new JButton();
        buttonRanquing.setText("Rànquing");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(buttonRanquing, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel3, BorderLayout.EAST);
        buttonNormes = new JButton();
        buttonNormes.setText("Normes");
        panel3.add(buttonNormes);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        panel.add(panel4, BorderLayout.CENTER);
        buttonNovaPartida = new JButton();
        buttonNovaPartida.setText("Nova Partida");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(buttonNovaPartida, gbc);
        buttonCarregarPartida = new JButton();
        buttonCarregarPartida.setText("Carregar Partida");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(buttonCarregarPartida, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
