package presentation;

import javax.swing.*;
import java.awt.*;
import java.util.Arrays;

public class LoginView {
    private final ControladorPresentacio controladorPresentacio;
    private JPanel panel;
    private JButton buttonTorna;
    private JTextField textFieldNomUsuari;
    private JTextField textFieldContrasenya;
    private JButton buttonIniciaSessio;

    LoginView(ControladorPresentacio controladorPresentacio) {
        this.controladorPresentacio = controladorPresentacio;
        $$$setupUI$$$();
        initComponents();
    }

    void show() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Registre");
    }

    void initComponents() {
        buttonIniciaSessio.addActionListener(actionEvent -> iniciaSessioButtonClick());
        buttonTorna.addActionListener(actionEvent -> controladorPresentacio.showInitialView());
    }

    private void iniciaSessioButtonClick() {
        String username = textFieldNomUsuari.getText();
        String password = Arrays.toString(textFieldContrasenya.getPassword());
        /**
        if (algo q miri si la contra i l'user es corresponen)
            controladorPresentacio.showWarningDialog("Could not register", "Invalid input data");
        else {
            controladorPresentacio.logInUser(username, password); No existeix aquesta funcio pero hauria
            controladorPresentacio.showInitialView();
        }**/
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel.add(panel2, BorderLayout.NORTH);
        buttonTorna = new JButton();
        buttonTorna.setText("Torna");
        panel2.add(buttonTorna);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        panel.add(panel3, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setText("Nom d'usuari");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(label1, gbc);
        textFieldNomUsuari = new JTextField();
        textFieldNomUsuari.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 40, 0, 40);
        panel3.add(textFieldNomUsuari, gbc);
        textFieldContrasenya = new JTextField();
        textFieldContrasenya.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 40, 0, 40);
        panel3.add(textFieldContrasenya, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel3.add(spacer1, gbc);
        final JLabel label2 = new JLabel();
        label2.setEnabled(true);
        label2.setHorizontalAlignment(0);
        label2.setText("Contrasenya");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(label2, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel4, BorderLayout.SOUTH);
        buttonIniciaSessio = new JButton();
        buttonIniciaSessio.setText("Inicia Sessió");
        panel4.add(buttonIniciaSessio);
        label1.setLabelFor(textFieldNomUsuari);
        label2.setLabelFor(textFieldContrasenya);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
