package presentation;

import javax.swing.*;
import java.awt.*;

public class MainView {

    private final ControladorPresentacio controladorPresentacio;
    private JFrame frame;
    private JLabel text;
    private JButton button;
    private JButton changeButton;
    private JPanel panel;

    MainView(ControladorPresentacio controladorPresentacio) {
        this.controladorPresentacio = controladorPresentacio;
        $$$setupUI$$$();
        initComponents();
    }

    void init() {
        frame.setContentPane(panel);
        frame.setVisible(true);
        frame.setSize(new Dimension(400, 600));
    }

    private void initComponents() {
        frame = new JFrame("Mastermind");

        button.addActionListener(
                actionEvent -> text.setText("El botó ha estat apretat.")
        );
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        text = new JLabel();
        text.setText("Label");
        panel.add(text);
        button = new JButton();
        button.setText("Button");
        panel.add(button);
        changeButton = new JButton();
        changeButton.setText("Button");
        panel.add(changeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
