package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class NormesView {
    private final ControladorPresentacio controladorPresentacio;
    private JPanel panel;
    private JButton buttonTorna;

    NormesView(ControladorPresentacio controladorPresentacio) {
        this.controladorPresentacio = controladorPresentacio;
        $$$setupUI$$$();
        initComponents();
    }

    void show() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Normes del Joc");
    }

    void initComponents() {

        buttonTorna.addActionListener(actionEvent -> controladorPresentacio.showHomeView()); //TODO: On torna depen de si hi ha usuari logged
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel.add(panel1, BorderLayout.NORTH);
        buttonTorna = new JButton();
        buttonTorna.setText("Torna");
        panel1.add(buttonTorna);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel.add(panel2, BorderLayout.CENTER);
        final JTextPane textPane1 = new JTextPane();
        textPane1.setEditable(false);
        textPane1.setText("Normes del Mastermind");
        panel2.add(textPane1, BorderLayout.NORTH);
        final JTextPane textPane2 = new JTextPane();
        textPane2.setEditable(false);
        textPane2.setText("lapx xwxm weiokx owj wdecjicj ie x eje ce cjed jcei weweioewc, x wexe.");
        panel2.add(textPane2, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
