package presentation;

import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class NovaPartidaView {

    private final ControladorPresentacio controladorPresentacio;
    private JPanel panel;
    private JButton buttonTorna;
    private NovaPartidaMakerPanel panelMaker;
    private JButton buttonJuga;
    private JSlider sliderDificultat;
    private JTabbedPane tabbedPane;
    private NovaPartidaBreakerPanel panelBreaker;

    NovaPartidaView(ControladorPresentacio controladorPresentacio) {
        this.controladorPresentacio = controladorPresentacio;
        $$$setupUI$$$();
        initComponents();
    }

    void show() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Registre");
    }

    void initComponents() {

        buttonTorna.addActionListener(actionEvent -> controladorPresentacio.showHomeView());
        buttonJuga.addActionListener(actionEvent -> jugaButtonClick());
    }

    private void jugaButtonClick() { //TODO: cridar creacio de partida i canviar de view

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        tabbedPane = new JTabbedPane();
        tabbedPane.setTabPlacement(1);
        panel.add(tabbedPane, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane.addTab("Breaker", panel1);
        panelBreaker = new NovaPartidaBreakerPanel();
        panel1.add(panelBreaker.$$$getRootComponent$$$(), BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        tabbedPane.addTab("Maker", panel2);
        panelMaker = new NovaPartidaMakerPanel();
        panel2.add(panelMaker.$$$getRootComponent$$$());
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel.add(panel3, BorderLayout.NORTH);
        buttonTorna = new JButton();
        buttonTorna.setText("Torna");
        panel3.add(buttonTorna);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel4, BorderLayout.SOUTH);
        buttonJuga = new JButton();
        buttonJuga.setText("Juga!");
        panel4.add(buttonJuga);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
