package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.util.Hashtable;

public class NovaPartidaBreakerPanel extends JPanel {

    private JPanel panel;
    private JSlider sliderDificultat;
    private Integer dificultat;

    NovaPartidaBreakerPanel() {
        $$$setupUI$$$();
        initComponents();
    }

    void initComponents() {
        initSlider();
    }

    private void initSlider() {
        Hashtable<Integer, JLabel> labelTable = new Hashtable<Integer, JLabel>();
        labelTable.put(1, new JLabel("Facil"));
        labelTable.put(2, new JLabel("Mitja"));
        labelTable.put(3, new JLabel("Dificil"));
        sliderDificultat.setLabelTable(labelTable);
    }

    Integer getDificultat() {
        return sliderDificultat.getValue();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JLabel label1 = new JLabel();
        label1.setText("Dificultat:");
        panel.add(label1, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(panel1, BorderLayout.CENTER);
        sliderDificultat = new JSlider();
        sliderDificultat.setMajorTickSpacing(3);
        sliderDificultat.setMaximum(3);
        sliderDificultat.setMinimum(1);
        sliderDificultat.setMinorTickSpacing(1);
        sliderDificultat.setPaintLabels(true);
        sliderDificultat.setPaintTicks(false);
        sliderDificultat.setPaintTrack(true);
        sliderDificultat.setValue(2);
        panel1.add(sliderDificultat, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
