package presentation;

import javax.swing.*;
import java.awt.*;
import java.util.Hashtable;

class NovaPartidaBreakerPanel extends JPanel {

    private JPanel panel;
    private JSlider sliderDificultat;

    NovaPartidaBreakerPanel() {
        $$$setupUI$$$();
        initComponents();
    }

    private void initComponents() {
        initSlider();
    }

    private void initSlider() {
        Hashtable<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(1, new JLabel("Facil"));
        labelTable.put(2, new JLabel("Mitja"));
        labelTable.put(3, new JLabel("Dificil"));
        sliderDificultat.setLabelTable(labelTable);
    }

    Integer getDificultat() {
        return sliderDificultat.getValue();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        panel.add(panel1, gbc);
        sliderDificultat = new JSlider();
        sliderDificultat.setMajorTickSpacing(3);
        sliderDificultat.setMaximum(3);
        sliderDificultat.setMinimum(1);
        sliderDificultat.setMinorTickSpacing(1);
        sliderDificultat.setPaintLabels(true);
        sliderDificultat.setPaintTicks(false);
        sliderDificultat.setPaintTrack(true);
        sliderDificultat.setValue(2);
        panel1.add(sliderDificultat);
        final JLabel label1 = new JLabel();
        label1.setText("Dificultat");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
