package presentation;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.ArrayList;

public class RankingView {
    private final ControladorPresentacio controladorPresentacio;
    private JPanel panel;
    private JButton buttonTorna;
    private JTabbedPane tabbedPane;

    private ArrayList<JPanel> rankingPanelList;

    private List<List<List<String>>> ranking;

    RankingView() {
        controladorPresentacio = ControladorPresentacio.getInstance();
        $$$setupUI$$$();
        initComponents();
    }

    private void initComponents(){
        initRankingPanelList();
        initTabbedPanel();
        initRanking();
    }

    private void initRanking(){
        ranking = controladorPresentacio.getRanquing();
    }

    private void initRankingPanelList(){
        rankingPanelList = new ArrayList<>();
        for (int i = 0; i < 4; ++i) rankingPanelList.add(new JPanel());
    }

    private void initTabbedPanel(){
        tabbedPane.addTab("Fàcil", rankingPanelList.get(0));
        tabbedPane.addTab("Mig", rankingPanelList.get(1));
        tabbedPane.addTab("Difícil", rankingPanelList.get(2));
        tabbedPane.addTab("Total", rankingPanelList.get(3));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel.add(panel1, BorderLayout.NORTH);
        buttonTorna = new JButton();
        buttonTorna.setText("Torna");
        panel1.add(buttonTorna);
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 10, 0, 10), -1, -1));
        panel.add(panel2, BorderLayout.CENTER);
        tabbedPane = new JTabbedPane();
        panel2.add(tabbedPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("Untitled", panel3);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("Untitled", panel4);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
