package presentation;

import javax.swing.*;
import java.awt.*;

public class RegisterView {

    private final ControladorPresentacio controladorPresentacio;
    private JLabel label;
    private JPanel panel;

    RegisterView(ControladorPresentacio controladorPresentacio) {
        this.controladorPresentacio = controladorPresentacio;
        $$$setupUI$$$();
        initComponents();
    }

    void init() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Registre");
    }

    void initComponents() {

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        label = new JLabel();
        label.setEnabled(true);
        label.setText("Això és un label de prova");
        panel.add(label);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
