package presentation;

import javax.swing.*;
import java.awt.*;

/**
 * Vista del Registre d'un usuari
 *
 * @author Albert Canales
 */
class RegisterView {

    /**
     * Controlador de presentació
     */
    private final ControladorPresentacio controladorPresentacio;

    /**
     * Panell contenidor
     */
    private JPanel panel;

    /**
     * Camp de text pel nom d'usuari
     */
    private JTextField textFieldNomUsuari;

    /**
     * Camp de text pel nom complet
     */
    private JTextField textFieldNomComplet;

    /**
     * Camp de text per la contrasenya
     */
    private JPasswordField textFieldContrasenya;

    /**
     * Botó per registrar l'usuari
     */
    private JButton buttonRegistra;

    /**
     * Botó per tornar a la vista anterior
     */
    private JButton buttonTorna;

    /**
     * Constructor per defecte de la vista
     */
    RegisterView() {
        controladorPresentacio = ControladorPresentacio.getInstance();
        $$$setupUI$$$();
        initComponents();
    }

    /**
     * Mètode per mostrar la vista
     */
    void show() {
        controladorPresentacio.setContent(panel);
        controladorPresentacio.setTitle("Registrar un usuari");
    }

    /**
     * Mètode per inicialitzar els components de la vista
     */
    private void initComponents() {
        buttonRegistra.addActionListener(actionEvent -> registraButtonClick());

        buttonTorna.addActionListener(actionEvent -> controladorPresentacio.showInitialView());
    }

    /**
     * Mètode que efectua les accions pertinents en clicar el botó per registrar-se
     */
    private void registraButtonClick() {
        String username = textFieldNomUsuari.getText();
        String name = textFieldNomComplet.getText();
        String password = String.valueOf(textFieldContrasenya.getPassword());

        if (!controladorPresentacio.isValidUsername(username))
            controladorPresentacio.showWarningDialog("No s'ha pogut registrar",
                    "El nom d'usuari no és vàlid");
        else if (!controladorPresentacio.isValidName(name))
            controladorPresentacio.showWarningDialog("No s'ha pogut registrar",
                    "El nom complet no és vàlid");
        else if (!controladorPresentacio.isValidPassword(password))
            controladorPresentacio.showWarningDialog("No s'ha pogut registrar",
                    "La contrasenya no és vàlida");
        else if (controladorPresentacio.existsUser(username))
            controladorPresentacio.showWarningDialog("No s'ha pogut registrar",
                    "Ja existeix un usuari amb el mateix nom d'usuari");
        else {
            controladorPresentacio.registerUser(username, name, password);
            controladorPresentacio.loginUser(username, password);
            controladorPresentacio.showHomeView();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel.add(panel1, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setEnabled(true);
        label1.setText("Nom d'usuari");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        panel1.add(label1, gbc);
        textFieldNomUsuari = new JTextField();
        textFieldNomUsuari.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 40, 0, 40);
        panel1.add(textFieldNomUsuari, gbc);
        textFieldNomComplet = new JTextField();
        textFieldNomComplet.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 40, 0, 40);
        panel1.add(textFieldNomComplet, gbc);
        final JLabel label2 = new JLabel();
        label2.setEnabled(true);
        label2.setText("Contrasenya");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        panel1.add(label2, gbc);
        textFieldContrasenya = new JPasswordField();
        textFieldContrasenya.setHorizontalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 40, 0, 40);
        panel1.add(textFieldContrasenya, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(spacer2, gbc);
        final JLabel label3 = new JLabel();
        label3.setEnabled(true);
        label3.setText("Nom complet");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        panel1.add(label3, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(panel2, BorderLayout.SOUTH);
        buttonRegistra = new JButton();
        buttonRegistra.setText("Registra't");
        panel2.add(buttonRegistra);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel.add(panel3, BorderLayout.NORTH);
        buttonTorna = new JButton();
        buttonTorna.setText("Torna");
        panel3.add(buttonTorna);
        label1.setLabelFor(textFieldNomUsuari);
        label2.setLabelFor(textFieldContrasenya);
        label3.setLabelFor(textFieldNomComplet);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
