package presentation;

import javax.swing.*;
import java.awt.*;

/**
 * Representació d'una seqüència del joc en la interfície de Swing
 * @author Albert Canales Ros
 */
public class SequenciaPanel extends Subject {

    /**
     * Panell contenidor
     */
    private JPanel panel;

    /**
     * Primera bola de la seqüència
     */
    private BolaButton bolaButton1;

    /**
     * Segona bola de la seqüència
     */
    private BolaButton bolaButton2;

    /**
     * Tercera bola de la seqüència
     */
    private BolaButton bolaButton3;

    /**
     * Quarta bola de la seqüència
     */
    private BolaButton bolaButton4;

    /**
     * Constructor per defecte de la seqüència. No assigna color a cap de les boles
     */
    SequenciaPanel() {

        $$$setupUI$$$();
        bolaButton1.setBolaColor(BolaColor.RED);
        bolaButton2.setBolaColor(BolaColor.GREEN);
        bolaButton3.setBolaColor(BolaColor.BLUE);
        bolaButton4.setBolaColor(BolaColor.NONE);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        bolaButton1 = new BolaButton();
        panel.add(bolaButton1.$$$getRootComponent$$$());
        bolaButton2 = new BolaButton();
        panel.add(bolaButton2.$$$getRootComponent$$$());
        bolaButton3 = new BolaButton();
        panel.add(bolaButton3.$$$getRootComponent$$$());
        bolaButton4 = new BolaButton();
        panel.add(bolaButton4.$$$getRootComponent$$$());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
